//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCATION()
        {
            this.EVENTs = new HashSet<EVENT>();
            this.MEMBERs = new HashSet<MEMBER>();
        }
    
        public short ID_LOCATION { get; set; }
        public string LOCATION_NAME { get; set; }
        public string CATEGORY { get; set; }
        public string DETAIL { get; set; }
        public string PICTURE { get; set; }
        public Nullable<System.DateTime> TIME_START_L { get; set; }
        public Nullable<System.DateTime> TIME_END_L { get; set; }
        public string ADDRESS { get; set; }
        public string FACILITY { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<int> AREA { get; set; }
        public Nullable<short> PROMOTE_L_ID { get; set; }
    
        public string Owner_location { get; set; }
        public string S_DATE { get; set; }
        public string E_DATE { get; set; }

        public virtual PROMOTE_L PROMOTE_L { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT> EVENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMBER> MEMBERs { get; set; }
    }
}
